### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by cedriczirtacic**

### CODE REVIEW

**Comment by Wouter0100** [comment]
Unacceptable. Please use a proper commit message and PR title. :+1:

**Comment by gytdau** [comment]
Using both 'Unacceptable' and a thumbs up emoji in a comment is unacceptable. :+1:

**Comment by Wouter0100** [comment]
What do you mean? :-1:

**Comment by gytdau** [comment]
:+1: Cheeky editing of comments is acceptable. Unacceptable. :-1:

**Pull request merged**
