### PR TITLE
Add additional forms of Hebrew

### PR DESCRIPTION
**Pull request by lanzkron**
- It only included the feminine form of 13 in Hebrew, while the feminine form is the default for numbers, when counting masculine things the masculine form should be used.  
- Added Gematria

### CODE REVIEW

**Comment by OfekA** [comment]
Fully agree

**Comment by aarongreenwald** [comment]
Don't you have to address non-standard forms of gematria? ט"ד, ח"ה, etc are technically valid forms of 13. 

Further research reveals that there are a whole bunch of other forms I was unaware of. I think this PR is entirely incomplete. 

https://en.wikipedia.org/wiki/Gematria#Methods

**Comment by OfekA** [comment]
Only disbelievers might say those since they are not correct and polite
towards god. We don't care about them. /s

On Sun, Mar 27, 2016, 19:23 Aaron Greenwald <notifications@github.com>
wrote:

> Don't you have to address non-standard forms of gematria? ט"ד, ח"ה, etc
> are technically valid forms of 13.
>
> Further research reveals that there are a whole bunch of other forms I was
> unaware of. I think this PR is entirely incomplete.
>
> https://en.wikipedia.org/wiki/Gematria#Methods
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/jezen/is-thirteen/pull/226#issuecomment-202109485>
>
-- 
Best,
Ofek

**Comment by lanzkron** [comment]
Old joke is old.

**Pull request closed without merging**
