### PR TITLE
Update to use correct syntax in tests

### PR DESCRIPTION
**Pull request by Drarok**
Honestly, this level of inconsistency just will not do!

### CODE REVIEW

**Comment by gytdau** [comment]
I think you meant:
`is(x).thirteen()`

instead of

`isThirteen(x).thirteen()`

**Comment by Drarok** [comment]
I suppose `is` would be ok for the tests, but perhaps there needs to be a discussion around the "correct" name to require it as in production? `is` seems a bit too vague.

**Comment by gytdau** [comment]
Hmm, I can't think of anything.

**Comment by gytdau** [comment]
This is also being discussed in #39

**Comment by jezen** [comment]
@Drarok @gytdau I think you are both correct and your opinions are equal <sub>to thirteen</sub>

**Comment by Drarok** [comment]
Unacceptable, this issue, #35 is closer to 13, so must be considered more correct!

**Comment by gytdau** [comment]
:( Oh well

**Comment by Drarok** [comment]
Loads more tests have been added since with the old syntax, so I'm withdrawing all my contributions! ;)

**Comment by gytdau** [comment]
#MoveFastAndBreakThings

**Pull request closed without merging**
