### PR TITLE
Added dutch and moved all string tests to an array

### PR DESCRIPTION
**Pull request by Wouter0100**

### CODE REVIEW

**Comment by Wouter0100** [comment]
Oeps. Forgot to add tests.

**Comment by jezen** [comment]
@Wouter0100 is very nice PR but cam u please add language support for Double Dutch

**Comment by jseminck** [comment]
This should have been two commits, really... but other than that, very nice PR indeed!

1/ Add support for Dutch.
2/ Move to array

**Comment by gytdau** [comment]
This commit is no longer compatible since #34 :disappointed:

**Pull request closed without merging**
