### PR TITLE
Add support for Olivia Wilde

### PR DESCRIPTION
**Pull request by nicolas-besnard**
[The real 13](http://images.teamsugar.com/files/upl0/1/13839/05_2008/house402_scene-13_7741_f.preview.jpg)

### CODE REVIEW

**Comment by nicolas-besnard** [comment]
Fix #60

**Comment by gytdau** [comment]
Doesn't work. "Olivia Wilde" is in capital letters wheras all text is lowercased before being checked in array. Very unacceptable.

**Comment by nicolas-besnard** [comment]
It can't fail, it was developed with strict TDD.

**Comment by gytdau** [comment]
Oh Christ Reddit is here

**Comment by katastic** [comment]
Wouldn't this project be more secure if it was re-written in Rust?

**Comment by TheZoq2** [comment]
Not just more secure, also faster

**Pull request merged**
