### PR TITLE
comparison for all base types

### PR DESCRIPTION
**Pull request by kapadiamush**
Should take care of adding in literal strings for every possible base type between 2 and 36.

### CODE REVIEW

**Comment by dehli** [comment]
As long as it works for base 13, I'll be happy.

**Comment by gytdau** [comment]
What happens at base 37?

**Comment by kapadiamush** [comment]
`parseInt` doesn't work for it :joy:

**Comment by dehli** [comment]
http://stackoverflow.com/questions/13234867/maximum-base-for-parseint

**Pull request merged**
