### PR TITLE
Added new languages

### PR DESCRIPTION
**Pull request by caiodias**
Add Portuguese and French.

### CODE REVIEW

**Comment by Wouter0100** [comment]
Tests would be nice.

**Comment by caiodias** [comment]
Wait, I will add the tests. Sorry.

**Comment by caiodias** [comment]
Done.

**Comment by Wouter0100** [comment]
There are some conflicts. Could you please rebase it against master? :8ball:

**Comment by caiodias** [comment]
I'm sorry, I tried but I believe that I wasn't successful.

**Comment by AaronCritchley** [comment]
I have this covered in PR #45 :smile:

**Comment by gytdau** [comment]
Well thanks for trying anyway @caiodias.

**Pull request closed without merging**
