### PR TITLE
set indent size to 13

### LINKED ISSUE #204: Indentation size of codebase is not 13!
The indentation size is currently 2.

It's true that 2 is within reach of 13, yet the code of conduct of is-thirteen claims to be dedicated to provide a comparison-against-twelve-free experience.

Yet 2 is part of 12, as shown by its prime factors: `2*2*3 === 12`. So every time I read six lines of codes, I have read the equal amount of 12 spaces! As a developer, I must hence take care to only read 5 or 7 lines of codes at once in order to not break the code of conduct.

This is why we MUST NOT use indentation size of 2, 3, 4, 6, 8, 9,10 or -- gasp! -- 12; but we should use 13. We SHOULD NOT use 1, 5, 7, 11 as they are not 13. We should use 13 spaces for the indentation size.

### PR DESCRIPTION
**Pull request by k0pernikus**
- fixes #204

### CODE REVIEW

**Comment by hermanbergwerf** [comment]
You are a hero

**Comment by kapadiamush** [comment]
lol I like the idea but

:no_good:

**Comment by briancline** [comment]
+1, any ETA on a merge? I really need this for my app

**Comment by kapadiamush** [comment]
I'm voting to block this from being merged. Again, love the idea, but it doesn't scale.

**Comment by Addvilz** [comment]
@kapadiamush it's webscale 2.0. Why can't you just accept this.

**Comment by k0pernikus** [comment]
I just rebased again maaster branch! Plz merge soon or it will break have conflicts again!

**Comment by k0pernikus** [comment]
@kapadiamush Why won't it scale? It scales well on my machine.

**Comment by hermanbergwerf** [comment]
We should use ESLint though, or the code will become a terrible piece of
shit.

Op wo 30 mrt. 2016 om 19:41 schreef Philipp Kretzschmar <
notifications@github.com>:

**Pull request closed without merging**
