### PR TITLE
i18n improvements, enabling people around the world to enjoy 13

### PR DESCRIPTION
**Pull request by AaronCritchley**
Fair warning that most have not been tested, happy to add in tests if anyone would like them.

### CODE REVIEW

**Comment by Wouter0100** [comment]
Tests would be nice.

**Comment by AaronCritchley** [comment]
OK, will add tests within the next few hours.

**Comment by AaronCritchley** [comment]
Tests added, I'm unable to test locally at the moment, so if you get chance @Wouter0100 would be great if you could go ahead.

**Comment by gytdau** [comment]
Sorry, you have to rebase against master :(

**Comment by AaronCritchley** [comment]
@gytdau done. 

Let me know if there are any other problems :smile:

**Comment by gytdau** [comment]
Thanks :+1:

**Pull request merged**
