### PR TITLE
Add Roman Urdu variant

### PR DESCRIPTION
**Pull request by armujahid**
I have added [Roman Urdu](https://en.wikipedia.org/wiki/Roman_Urdu) variant of 13 in constants
Proof: https://www.google.com/search?q=roman+urdu+tayra

### CODE REVIEW

**Comment by armujahid** [comment]
I will amend this commit to also include tests. Please don't merge it for now.

**Comment by armujahid** [comment]
Done. Now its ready to merge

**Comment by armujahid** [comment]
Kindly review and merge it :)

**Comment by armujahid** [comment]
Kindly review and merge this :)

**Comment by armujahid** [comment]
Kindly review and merge this :)

**Review by Almenon — APPROVED** [review]

**Comment by Almenon** [comment]
شکریہ!

**Pull request merged**
