### PR TITLE
add Dilma 13 - President of Brazil

### PR DESCRIPTION
**Pull request by arthurcamara1**
Ref:
https://www.google.ca/search?q=dilma+13

### CODE REVIEW

**Comment by filipedumont** [comment]
:-1:

**Comment by matbhz** [comment]
Lacrality

**Comment by konkked** [comment]
Could you add a test case for this pull request, thx

**Comment by arthurcamara1** [comment]
Test is here https://github.com/jezen/is-thirteen/pull/320
Could you merge both? cc @konkked

**Pull request merged**
