### PR TITLE
Support monkey to use

### PR DESCRIPTION
**Pull request by skilliscode**
Monkey might not know the number characters but it could use a symbol to count as 13.
e.g. '|||||||||||||'

### CODE REVIEW

**Comment by konkked** [comment]
This was already handled with the implementation of issue #265

**Comment by konkked** [comment]
Sorry, read the code you put in, include a test and I will merge it.

**Comment by kapadiamush** [comment]
We should implement this functionality through `lodash`.

**Comment by skilliscode** [comment]
@konkked added the tests.
@kapadiamush prefer keep it simple & stupid, leave it without dependences.

**Pull request merged**
