### PR TITLE
Add 1.3 to 13 strings

### PR DESCRIPTION
**Pull request by codingJWilliams**
I mean its basically 13 guys

### CODE REVIEW

**Comment by Almenon** [comment]
Nice try, but 1.3 **is not** 13.  Here at is-thirteen we take ourselves very seriously, and only PR's of the highest quality will be accepted.

If you could prove 1.3 is 13 then I might be persuaded.... :P

**Comment by codingJWilliams** [comment]
13 × 0 = 1.3 × 0
13 × 0 ÷ 0 = 1.3 × 0 ÷ 0
13 = 1.3

**Comment by Almenon** [comment]
Wow, nice proof! :D

Fix the merge conflicts and I'll accept the PR.

**Comment by codingJWilliams** [comment]
Done!

**Pull request merged**
