### PR TITLE
Deep13: Deep Learning Image Classification for Pictures of the Number 13

### PR DESCRIPTION
**Pull request by Tylersuard**
This is a Tensorflow image classifier, used to determine whether or not an image is a picture of the number 13.

### CODE REVIEW

**Comment by Almenon** [comment]
small world - you're the same person I just emailed about a week ago!

https://i.imgur.com/FvU1Yrn.png

You accidentily checked in your pytest cache files btw.

**Comment by Tylersuard** [comment]
Haaaa now THAT is funny.  I found your business card in my wallet today
when I was buying In-N-Out.  Spooky.

**Comment by jezen** [comment]
Fabulous work brethren.

I shall sing your name from the rooftops.

Once, twice, thirteen times a Tyler.

**Comment by Tylersuard** [comment]
Huzzah!!!

**Comment by Tylersuard** [comment]
Hey, long time no talk.  I just wanted to alert you to the fact that
is-thirteen is now being stored in Microsoft's Arctic Vault.  Now, in case
of an apocalypse, future generations will know whether a number is thirteen.
Excellent work, sir.

BTW, how is work, coding, etc?

**Comment by jezen** [comment]
> BTW, how is work, coding, etc?

@Tylersuard I am hard at work researching [instances of thirteen in the reinsurance industry](https://serokell.io/blog/haskell-in-industry-riskbook).

A blessed thirteen unto you all ❤️ 1️⃣ 3️⃣

**Pull request merged**
